name: E2E - Content API to Amplify

on:
  push:
    branches: [dev]
    paths: ['.github/run-e2e']

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: echo "Workflow triggered successfully"